services:
  localstack:
    image: localstack/localstack:2.3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      - "localstack-data:/var/lib/localstack"
volumes:
  localstack-data:
