version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-srta}
      POSTGRES_USER: ${POSTGRES_USER:-srta}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-srta_pw}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-srta} -d ${POSTGRES_DB:-srta}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: