name: docker-publish

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

env:
  API_IMAGE: ghcr.io/${{ github.repository_owner }}/srta-api
  WEB_IMAGE: ghcr.io/${{ github.repository_owner }}/srta-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.API_IMAGE }}
            ${{ env.WEB_IMAGE }}

      - name: Build+Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile.api
          push: true
          tags: |
            ${{ env.API_IMAGE }}:${{ steps.meta.outputs.version }}
            ${{ env.API_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build+Push Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/Dockerfile.web
          push: true
          tags: |
            ${{ env.WEB_IMAGE }}:${{ steps.meta.outputs.version }}
            ${{ env.WEB_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_API_BASE=${{ vars.NEXT_PUBLIC_API_BASE || 'http://localhost:8000/api/v1' }}
